
version: '3'

services:
  db:
    container_name: postgres
    image: postgres:14
    ports:
      - "5432:5432"
    volumes:
      - db-data:/var/lib/postgresql/data
      - ./docker-script:/docker-entrypoint-initdb.d # First DB Script
    environment:
      - POSTGRES_PASSWORD=test # SuperUser Password

volumes:
  db-data: